// Generated by CoffeeScript 1.6.2
(function() {
  var fixed;

  fixed = function(str, len, app) {
    if (app == null) {
      app = ' ';
    }
    str = String(str);
    while (str.length < len) {
      str += app;
    }
    return str;
  };

  module.exports = function(app) {
    var c1, c2, cl, route, routes, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _results;

    c1 = 'Path'.length;
    c2 = 'Controller'.length;
    routes = app.routes.get.concat(app.routes.post);
    for (_i = 0, _len = routes.length; _i < _len; _i++) {
      route = routes[_i];
      c1 = Math.max(c1, (_ref = (_ref1 = route.path) != null ? _ref1.length : void 0) != null ? _ref : 0);
      c2 = Math.max(c2, (_ref2 = (_ref3 = route.controller) != null ? _ref3.length : void 0) != null ? _ref2 : 0);
    }
    cl = c1 + c2 + 3;
    trace("[xsp] Routes " + (fixed('', cl - 13, '-')));
    trace.yellow("" + (fixed('Path', c1)) + "   " + (fixed('Controller', c1)));
    trace.yellow("" + (fixed('', cl, '-')));
    _results = [];
    for (_j = 0, _len1 = routes.length; _j < _len1; _j++) {
      route = routes[_j];
      _results.push(trace.yellow("" + (fixed(route.path, c1)) + "   " + (fixed(route.controller, 2))));
    }
    return _results;
  };

}).call(this);
