// Generated by CoffeeScript 1.6.2
(function() {
  var ncp;

  ncp = require('ncp').ncp;

  module.exports = function() {
    var argv, opts;

    opts = require('optimist').usage('Usage: xsp --create [target] --language [language] ').describe('create', 'Create an sample application').alias('c', 'create').describe('language', 'javascript / coffeescript').alias('l', 'language').describe('help', 'Show this help').alias('h', 'help')["default"]('language', 'javascript');
    argv = opts.argv;
    if (argv.help) {
      opts.showHelp();
      return;
    }
    if (argv.language === 'coffeescript') {
      return ncp("" + __dirname + "/../setup_coffee", argv.create, function(err) {
        if (err) {
          return console.error(err);
        } else {
          return console.log('Done');
        }
      });
    } else {
      return ncp("" + __dirname + "/../setup", argv.create, function(err) {
        if (err) {
          return console.error(err);
        } else {
          return console.log('Done');
        }
      });
    }
  };

}).call(this);
