// Generated by CoffeeScript 1.6.2
(function() {
  Object.defineProperty(Function.prototype, 'property', {
    value: function(prop, desc) {
      var c, sup, _ref, _ref1, _ref2, _ref3;

      if (desc) {
        if (desc instanceof Function) {
          desc = desc();
        }
        if (this.__super__) {
          c = this.__super__;
          while (c) {
            sup = Object.getOwnPropertyDescriptor(c, prop);
            if (sup) {
              break;
            }
            c = c.constructor.__super__;
          }
          if (sup) {
            if ((_ref = desc.configurable) == null) {
              desc.configurable = sup.configurable;
            }
            if ((_ref1 = desc.enumerable) == null) {
              desc.enumerable = sup.enumerable;
            }
            if ((_ref2 = desc.get) == null) {
              desc.get = sup.get;
            }
            if ((_ref3 = desc.set) == null) {
              desc.set = sup.set;
            }
          }
        }
        return Object.defineProperty(this.prototype, prop, desc);
      } else {
        return Object.getOwnPropertyDescriptor(this, prop);
      }
    },
    enumerable: false
  });

  Object.defineProperty(Function.prototype, 'noop', {
    value: function() {}
  });

}).call(this);
