// Generated by CoffeeScript 1.6.2
(function() {
  var decimalAdjust, __ceil, __floor, __round;

  decimalAdjust = function(type, value, exp) {
    if (exp === void 0 || +exp === 0) {
      return Math[type](value);
    }
    value = +value;
    exp = +exp;
    if (isNaN(value) || !(typeof exp === 'number' && exp % 1 === 0)) {
      return NaN;
    }
    value = value.toString().split('e');
    value = Math[type](+(value[0] + 'e' + (value[1] ? +value[1] - exp : -exp)));
    value = value.toString().split('e');
    return +(value[0] + 'e' + (value[1] ? +value[1] + exp : exp));
  };

  __round = Math.round;

  Math.round = function(value, decimal) {
    if (decimal) {
      return decimalAdjust('round', value, decimal * -1);
    } else {
      return __round(value);
    }
  };

  __floor = Math.floor;

  Math.floor = function(value, decimal) {
    if (decimal) {
      return decimalAdjust('floor', value, decimal * -1);
    } else {
      return __floor(value);
    }
  };

  __ceil = Math.ceil;

  Math.ceil = function(value, decimal) {
    if (decimal) {
      return decimalAdjust('ceil', value, decimal * -1);
    } else {
      return __ceil(value);
    }
  };

}).call(this);
