// Generated by CoffeeScript 1.6.2
(function() {
  global.String.prototype.multiply = function(count, separator) {
    var out;

    out = '';
    while (i < count) {
      if (out.length > 0 && separator) {
        out += separator;
      }
      out += this;
    }
    return out;
  };

  global.String.prototype.format = function(data) {
    return this.replace(new RegExp('{([^}]*)}', 'g'), function(p) {
      var r, _ref;

      r = p.substr(1, p.length - 2);
      return (_ref = data[r]) != null ? _ref : '';
    });
  };

  global.String.prototype.crop = function(length, add) {
    if (this.length > length) {
      return this.substr(0, length) + (add != null ? add : '');
    } else {
      return this;
    }
  };

  global.String.prototype.inject = function(index, text) {
    return this.substr(0, index) + text + this.substr(index);
  };

  global.String.prototype.escape = function() {
    return this.replace(/&(?!\w+;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };

}).call(this);
